### ISSUE TITLE
waitUntilEndOfMovement - axis_error

### ISSUE THREAD

**Issue by HojaeAhn** [sdss/lvmpwi#13]
When we use `offset` command, it waits until the mount is settled down.
It is done by `waitUntilEndOfMovement`, and tolerance (`axis_error`) should be given as the argument. 
The default of `axis_error` is 0.2 arcsec and the value used in `offset` is 0.1 arcsec.

Actually this value is too small. It takes long time (~1min) for mount to be settled down to this level.
The pixel scale of LVM system will be about 1 arcsec/pixel, so I think the optimal value of `axis_error` should be 0.3-0.5 arcsec.
This will be the minimum distance to be compensated in autoguide mode.

**Comment by wasndas** [comment]
Thanks for testing it on a non simulated mount. I have  set the default maximum axis error to 0.4 and added an extra parameter to the offset comand  --axis_error where you can overwrite the default.
