### ISSUE TITLE
30' difference between lvmpwi Dec and Astrometry.net Dec

### ISSUE THREAD

**Issue by mgjeon** [sdss/lvmpwi#15]
Please check this.

# Steps to Reproduce

1. Start lvmtan, lvmpwi, skymakercam, lvmcam
2. Goto RA, Dec in lvmpwi
3. lvmcam expose 
4. (Dec of lvmpwi) + 30' = (Dec of result image)

![lvmpwi](https://user-images.githubusercontent.com/88314422/161370043-62fde412-c67e-4eb5-81da-d2c4c8ef9097.PNG)
![astrometry](https://user-images.githubusercontent.com/88314422/161370044-23e1b165-3710-430d-85ba-bc17718e4623.PNG)

## lvmpwi
Tele RA (J2000): 12h 21m 54.40s
Tele Dec (J2000): +04° 28' 00.0"

## Astrometry.net Result
https://nova.astrometry.net/user_images/5772152#annotated
Center (RA, hms): 12h 21m 55.298s
Center (Dec, dms): +04° 57' 48.318"

## Query log
```
[WARNING]: [SCI.AGW]: Creating catalog path: /root/data/catalog/gaia
Gaia query:  SELECT source_id, ra,dec,phot_g_mean_mag FROM gaiaedr3.gaia_source WHERE phot_g_mean_mag <= 17 AND 1=CONTAINS(POINT('ICRS',ra,dec), CIRCLE('ICRS',185.476665012129,4.46666670883355, 0.692887394120578))
INFO: Query finished. [astroquery.utils.tap.core]
741 stars found within 0.692887394120578 deg
Downloading https://hpiers.obspm.fr/iers/bul/bulc/Leap_Second.dat
|===========================================| 1.3k/1.3k (100.00%)         0s
```

**Comment by wasndas** [comment]
Hmm, interresting. How do I start lvmcam ?

**Comment by wasndas** [comment]
... thats whats my colleague Max Haeberle answered:

> 
> ﻿Hi Florian,
> 
> this is actually what I would expect - my code calculates the guide images for a specific LVM pointing, defined as where the center of the IFU would be.
> 
> As the LVM guide cameras are off-axis, I would expect this offset to appear, if one is registering them at astrometry.net.
> 
> I think astrometry.net uses the center of the image to define the coordinates (and not the - for them - unknown center of the LVM field of view).
> 
> I worked out the math (see sketch in attachement), and I would expect a DEC offfset of 29.81 arcmin, which is exactly what appears in the example of the Korean team.
> 
> It will be the task of our focal plane metrology to get µm precise values for the real, as-built offsets.
> 
> Hope this helps,
> 
> Max


![image](https://user-images.githubusercontent.com/86017568/161564348-22ed2f74-e39f-4383-8317-68052a385693.png)

**Comment by mgjeon** [comment]
OK. I see why it happens. Thank you very much for checking it.
